### ISSUE TITLE
Possible issue in indexes in batch acquisition

### ISSUE THREAD

**Issue by matthewcarbone** [ziatdinovmax/gpax#43]
https://github.com/ziatdinovmax/gpax/blob/a35febaa3f0a33d276457b2ced198349f73560e1/gpax/acquisition/batch_acquisition.py#L45

Above, it looks like `X_` is either set to indexes or data. Should this read

```python
X_ = jnp.array(X[:, indices]) if indices is not None else jnp.array(X) 
```

or something like it? Just trying to understand a bit better what this is doing.

**Comment by ziatdinovmax** [comment]
This is for the situations where each (usually high-D) input data point has an index associated with it. For example, in DKL, we index image patches and, at each step, choose the index of a patch to measure next, even though our DKL inputs are actual images. Hence, the distance penalty must be applied to the (i, j) space of indices instead of the D image space.

**Comment by matthewcarbone** [comment]
I see, interesting. That could use some documentation but in that case it's not an issue. Thanks!
